name: Conditions
on: push
jobs:
    skip-or-run:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello"
              if: ${{ contains(github.run_id, '1') }} # ワークフロー実行IDで分岐
    fial:
        runs-on: ubuntu-latest
        steps:
            - run: exit 1   # 終了ステータスをゼロ以外なのでエラーが発生する。
            - run: echo "Hello"
              if: ${{ failure() }} # エラーが発生しても、failure関数があるので実行される