name: Auto Link Issue
on: pull_request
jobs:
  issue-linkes:
      runs-on: ubuntu-latest
      permissions:
          pull-requests: write
      timeout-minutes: 1
      steps:
          - uses: tkt-actions/add-issue-links@v1.8.1
            with:
              repo-token: "${{ secrets.GITHUB_TOKEN  }}"
              branch-prefix: "issue-"
              link-style: 'body'