name: Auto Link Issue
on: pull_request
jobs:
  checkout:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
        - uses: actions/checkout@v4
  link_issue_to_pr:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:              # GITHUB_TOKENの権限を設定
      pull-requests: write    # プルリクエストの書き込みを許可
      contents: read          # ソースコードの読み込みを許可
    if: ${{ startsWith(github.head_ref, 'issue-')}}
    steps:
      - id: source
        run: |
          ISSUE_NUM="${{ github.head_ref }}"
          ISSUE_NUM="${ISSUE_NUM:6}"
          echo "issue_num=$ISSUE_NUM" >> "$GITHUB_OUTPUT"
      - run: |
          CMD="gh api repos/${REPOSITORY}/issues/${ISSUE_NUM} -X PATCH -F pull_request=${PR_URL}"
          echo "Executing: $CMD"
          eval "$CMD"
        env:
          REPOSITORY: ${{ github.repository }}
          PR_URL: ${{ github.event.pull_request.url }}
          ISSUE_NUM: ${{ steps.source.outputs.issue_num }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
