name: Auto Link Issue
on: pull_request
jobs:
  checkout:
        runs-on: ubuntu-latest
        timeout-minutes: 1
        steps:
            - uses: actions/checkout@v4
  print:
        runs-on: ubuntu-latest
        timeout-minutes: 1
        steps:
            - run: echo '${{ toJson(github) }}'
  link_issuse:
        runs-on: ubuntu-latest
        timeout-minutes: 1
        if: ${{ startsWith(github.head_ref, 'issue-')}}
        steps:
            - id: sass
              run: echo "issue_num=${github.head_ref:6}" >> "${GITHUB_OUTPUT}"
            - run:
                echo issue_nume='${steps.source.outputs.issue_num}'
          