name: Auto Link Issue
on: pull_request
jobs:
  checkout:
        runs-on: ubuntu-latest
        timeout-minutes: 1
        steps:
            - uses: actions/checkout@v4
  print:
        runs-on: ubuntu-latest
        timeout-minutes: 1
        steps:
            - run: echo '${{ toJson(github) }}'
  link_issuse:
        runs-on: ubuntu-latest
        timeout-minutes: 1
        if: ${{ startsWith(github.head_ref, 'issue-')}}
        steps:
            - id: sass
              run: |
                ISSUE_NUM="${{ github.head_ref }}"
                ISSUE_NUM="${ISSUE_NUM:6}"
                echo "issue_num=$ISSUE_NUM" >> "$GITHUB_OUTPUT"
            - run:
                echo issue_num=${{ steps.source.outputs.issue_num }}
          