name: Auto Link Issue
on: pull_request
jobs:
  checkout:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
        - uses: actions/checkout@v4
  extract_issue:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: ${{ startsWith(github.head_ref, 'issue-')}}
    steps:
        - id: source
          run: echo "issue_num=${github.head_ref:6}" >> "${GITHUB_OUTPUT}"
        - run:
            echo ${{ steps.source.outputs.issue_num }}
          env:
            ISSUE_NUM: ${{ steps.source.outputs.issue_num }}
  link_issue_to_pr:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      pull-requests: write
      contents: read
    steps:
      - run: |
          gh api repos/${{ github.repository }}/issues/"${ISSUE_NUM}" -X PATCH -F "pull_request=${{ github.event.pull_request.url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub CLI用クレデンシャル
          

