name: Pull Request Link to Issue 
on: pull_request
jobs:
  issue-linkes:
      runs-on: ubuntu-latest
      permissions:
          pull-requests: write
          issues: read
      timeout-minutes: 1
      if: ${{ startsWith(github.head_ref, 'issue-') }}
      steps:
          - uses: tkt-actions/add-issue-links@v1.8.1
            with:
              repo-token: "${{ secrets.GITHUB_TOKEN  }}"
              branch-prefix: "issue-"
              link-style: 'body'
              resolve: 'true'
          - id: source
            run: |
                ISSUE_NUM="${{ github.head_ref }}"
                ISSUE_NUM="${ISSUE_NUM:6}"
                echo "issue_num=$ISSUE_NUM" >> "$GITHUB_OUTPUT"
          - run: |
                CMD="gh issue view ${ISSUE_NUM} --json body"
                echo "Executing: $CMD"
                eval "$CMD"
            env:
              ISSUE_NUM: ${{ steps.source.outputs.issue_num }}