name: Auto Link Issue
on: pull_request
jobs:
  checkout:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
        - uses: actions/checkout@v4
  extract_issue:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: ${{ startsWith(github.head_ref, 'issue-')}}
    steps:
      - id: source
        run: |
          ISSUE_NUM="${{ github.head_ref }}"
          ISSUE_NUM="${ISSUE_NUM:6}"
          echo "issue_num=$ISSUE_NUM" >> "$GITHUB_OUTPUT"
      - run: echo issue_num="${ISSUE_NUM}"
        env:
          ISSUE_NUM: ${{ steps.source.outputs.issue_num }}
  link_issue_to_pr:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      pull-requests: write
      contents: read
    steps:
      - run: |
          gh api repos/${{ github.repository }}/issues/"${ISSUE_NUM}" -X PATCH -F "pull_request=${{ github.event.pull_request.url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub CLI用クレデンシャル
          

