name: Manual
on:
    workflow_dispatch:                          # 手動実行イベント
        inputs:                         
            greeting:                           # 入力パラメーター名
                type: string                        # データ型（文字列）
                default: Hello                      # 入力パラメーターのデフォルト値
                required: true                      # 入力パラメーターの必須フラグ
                description: A cheerful word        # 入力パラメーターの概要
            flag:
                type: boolean
                default: true
                required: true
                description: "bool値の引数"
            log-level:
                type: choice                    # 入力パラメーターを特定の値に制限
                options:
                    - info
                    - warn
                    - error
                default: info
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "${{ inputs.greeting }}" # 入力パラメーター「greeting」の参照
                echo "${{ inputs.flag }}" # 入力パラメーター「flag」の参照
                echo "${{ inputs.log-level }}" # 入力パラメーター「log-level」の参照
            