name: Pull Request Body
on: pull_request
jobs:
    print:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            
            - name: Print PullRequest Body
              env: 
                PULL_REQUEST_BODY: ${{ github.event.pull_request.body }} 
              run: echo '${PULL_REQUEST_BODY}'
                 

    debug:
        runs-on: ubuntu-latest
        steps:
            - name: Dump GitHub Context
              run: echo '${{ toJson(github.event) }}'