name: Pull Request Body
on: pull_request
jobs:
    print:
        runs-on: ubuntu-latest
        steps:
            - run: echo '${PULL_REQUEST_BODY}'
              env: 
                PULL_REQUEST_BODY: ${{ github.event.pull_request.body }}    