name: Varibables
on: push
jobs:
    print:
        runs-on: ubuntu-latest
        env:
            USERNAME: ${{ vars.USERNAME }} # variablesの参照
            ABUSE_TEST: ${{ vars.ABUSE_TEST }}
        steps:
            - run: |
                "${USERNAME}"
                ${{ vars.ABUSE_TEST }}
                "${ABUSE_TEST}"